#!/bin/bash
#Hooks to monitor state

STATE_STARTING_CLIENT='python3 /opt/serverboi/scripts/patch_wf_embed.py change-stage --stage=Starting-Client'

STATE_VERIFY_CLIENT='python3 /opt/serverboi/scripts/patch_wf_embed.py change-stage --stage=Verifying-Client'